# frozen_string_literal: true

require_relative 'cancer_registry_reporting_test_kit/metadata'
require_relative 'inferno_requirements_tools/ext/inferno_core/runnable'
require_relative 'cancer_registry_reporting_test_kit/ehr_suite'
require_relative 'cancer_registry_reporting_test_kit/hdea_suite'
require_relative 'cancer_registry_reporting_test_kit/fhir_model_index_patch'
